export const productsData = [
  {
    id: 1,
    title: "Lorem ipsum",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: 14.9,
  },
  {
    id: 2,
    title: "dolor sit",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: 77.9,
  },
  {
    id: 3,
    title: "autem voluptates",
    quantity: 1,
    availableSizes: ["S", "XL"],
    price: 28.9,
  },
  {
    id: 4,
    title: "delectus ipsa",
    quantity: 1,
    availableSizes: ["L"],
    price: 32.9,
  },
  {
    id: 5,
    title: "beatae quia",
    quantity: 1,
    availableSizes: ["M", "L"],
    price: 65.9,
  },
  {
    id: 6,
    title: "velit officiis",
    quantity: 1,
    availableSizes: ["S", "M", "XL"],
    price: 98.9,
  },
  {
    id: 7,
    title: "nemo facilis",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: 33.9,
  },
  {
    id: 8,
    title: "Vel itaque",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: 75.9,
  },
  {
    id: 9,
    title: " In autem",
    quantity: 1,
    availableSizes: ["S", "M"],
    price: 24.9,
  },
];
