export const productsData = [
  {
    id: 1,
    title: "Product 1",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: "14.9 $",
  },
  {
    id: 2,
    title: "Product 2",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: "77.9 $",
  },
  {
    id: 3,
    title: "Product 3",
    quantity: 1,
    availableSizes: ["S", "XL"],
    price: "28.9 $",
  },
  {
    id: 4,
    title: "Product 4",
    quantity: 1,
    availableSizes: ["L"],
    price: "32.9 $",
  },
  {
    id: 5,
    title: "Product 5",
    quantity: 1,
    availableSizes: ["M", "L"],
    price: "65.9 $",
  },
  {
    id: 6,
    title: "Product 6",
    quantity: 1,
    availableSizes: ["S", "M", "XL"],
    price: "98.9 $",
  },
  {
    id: 7,
    title: "Product 7",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: "33.9 $",
  },
  {
    id: 8,
    title: "Product 8",
    quantity: 1,
    availableSizes: ["S", "M", "L"],
    price: "75.9 $",
  },
  {
    id: 9,
    title: "Product 9",
    quantity: 1,
    availableSizes: ["S", "M"],
    price: "24.9 $",
  },
];
